### ISSUE TITLE
API request goes to (wrong) relative path

### ISSUE THREAD

**Issue by RoelVB** [SharePoint/PnP-JS-Core#313]
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Expected / Desired Behavior / Question
When I do the following request from a SPFx webpart I would expect it to output the list's items.
```javascript
pnp.sp.web.lists.getByTitle('Test').get().then((data)=>{
  console.log(data);
});
```

#### Observed Behavior
`Unexpected end of JSON input`
Because the request goes to `/_layouts/15/_api/web/lists/getByTitle('Test')` instead of `/_api/web/lists/getByTitle('Test')`

#### Steps to Reproduce
Create a new SPFx webpart add a Sharepoint list request like illustrated above and run it from the Workbench.

**Comment by patrick-rodgers** [comment]
Hi @RoelVB - that is the incorrect query for getting a list's items, please see [this guide](https://github.com/SharePoint/PnP-JS-Core/wiki/Working-With:-Items).

However, this appears to be a bug related to the new workbench not having the _spPageContextInfo available. So will have a look. Things should work as expected in an actual SP page as a temp workaround.

**Comment by mauricionr** [comment]
Got same issue here in sharepoint online enviroment on workbench page.

```typescript
 pnp.setup({
      headers: { Accept: 'application/json;odata=verbose' }
    });
    pnp.sp.web.lists.ensure('ListTest').then(response => {
      response.list.items.add({ Title: 'adding' })
        .then(added => {
          response.list.items.get().then(items => {
            console.log(items)
          })
        })
    })
```

![image](https://cloud.githubusercontent.com/assets/2263551/22513591/d6aab5f6-e883-11e6-8abb-0b551bd0ce4e.png)

**Comment by RoelVB** [comment]
Thank you for your quick response @patrick-rodgers 

I intermediately tested it outside the workbench and it indeed works there. I'll use this workaround for now.

**Comment by patrick-rodgers** [comment]
Yes, this appears to be a bug - but I am working with engineering to see how best to fix. Issue is that the _spPageContextInfo is not exposed as a global on the page, but it is on the page (if you do a view source on workbench it is there). So trying to figure out if it should be a global OR if we need to get that information in a different way when operating inside SPFx.

**Comment by patrick-rodgers** [comment]
Well, actually I can't reproduce this - it appears to work fine for me on the workbench in layouts. Can you share your entire code? I am making the call within the render method of the webpart. I think we have identified the issue but I need to see it break to know it is fixed.

**Comment by mauricionr** [comment]
hey @patrick-rodgers i've uploaded my code to here

https://github.com/mauricionr/spfx-components/blob/master/components/search-component/src/webparts/searchBar/components/SearchBar.tsx#L14

**Comment by patrick-rodgers** [comment]
Ok, so you're doing it in the constructor of a component that is perhaps running on its own. Let me see if I can duplicate that. Thanks @mauricionr

**Comment by mauricionr** [comment]
yes @patrick-rodgers i've putted in the constructor just for a quick test and check if can reproduce the same issue as @RoelVB said

**Comment by RoelVB** [comment]
My code was inside the constructor. I've moved it to the render method, but still have the same issue.
Just for the record, I didn't have this issue with 1.0.6.

There is not much code to share. I've created a SPFx React project using Microsoft's Yeoman generator, added the PnP-JS library and then just added the piece of code from my first post.

**Comment by patrick-rodgers** [comment]
Nothing in the pipeline has changed from 1.0.6 to 2.0.0 that should affect this. Likely it is a changed behavior in the workbench/spfx affecting the library.

**Comment by patrick-rodgers** [comment]
So this is going to be interesting to fix. For now you can create a web directly using the application.shell.pageContext.web.absoluteUrl property.

The interesting part is that SPFx inits using a Promise, which we could in theory hook to get the application, but we would then need to make sure no requests get sent until we do that, but only when running inside SPFx. So we can either have a place where a user has to init the library with the url (I don't love that option) or reconfigure the library to have a loading promise (I don't love that option, but am leaning towards it).

Going to keep looking at this as obviously needs to be addressed somehow.

**Comment by patrick-rodgers** [comment]
Ok, have a fix for this, which took much more rewriting than I had hoped. I am still testing it but could one of you guys (or both :)) pull it from [my dev branch](https://github.com/patrick-rodgers/PnP-JS-Core/tree/dev) and give it a shot. Changes _should_ be invisible to you as a consumer.

**Comment by RoelVB** [comment]
I pulled you dev branch and tried to build it, gave me a lot of errors.

Part of it:
```
src\configuration\providers\spListConfigurationProvider.test.ts(3,30): error TS2307: Cannot find module '../../mocks/MockStorage'.
src\configuration\providers\spListConfigurationProvider.test.ts(8,1): error TS2304: Cannot find name 'describe'.
src\configuration\providers\spListConfigurationProvider.test.ts(10,5): error TS2304: Cannot find name 'describe'.
src\configuration\providers\spListConfigurationProvider.test.ts(15,9): error TS2304: Cannot find name 'beforeEach'.
src\configuration\providers\spListConfigurationProvider.test.ts(41,9): error TS2304: Cannot find name 'it'.
src\configuration\providers\spListConfigurationProvider.test.ts(42,60): error TS2345: Argument of type 'string' is not assignable to parameter of type 'Web'.
src\configuration\providers\spListConfigurationProvider.test.ts(46,9): error TS2304: Cannot find name 'it'.
src\configuration\providers\spListConfigurationProvider.test.ts(47,60): error TS2345: Argument of type 'string' is not assignable to parameter of type 'Web'.
src\configuration\providers\spListConfigurationProvider.test.ts(51,9): error TS2304: Cannot find name 'it'.
src\configuration\providers\spListConfigurationProvider.test.ts(53,60): error TS2345: Argument of type 'string' is not assignable to parameter of type 'Web'.
src\configuration\providers\spListConfigurationProvider.test.ts(80,9): error TS2304: Cannot find name 'it'.
src\configuration\providers\spListConfigurationProvider.test.ts(84,60): error TS2345: Argument of type 'string' is not assignable to parameter of type 'Web'.
src\configuration\providers\spListConfigurationProvider.ts(4,1): error TS1185: Merge conflict marker encountered.
src\configuration\providers\spListConfigurationProvider.ts(7,1): error TS1185: Merge conflict marker encountered.
src\configuration\providers\spListConfigurationProvider.ts(9,1): error TS1185: Merge conflict marker encountered.
src\configuration\providers\spListConfigurationProvider.ts(50,1): error TS1185: Merge conflict marker encountered.
```

**Comment by mauricionr** [comment]
@RoelVB try `npm install`

i pull the dev and I got a diferent behavior, i will test it tomorrow!

```
toor@linux-jpyk:~/workspace/PnP-JS-Core> gulp build
[13:05:58] Using gulpfile ~/workspace/PnP-JS-Core/gulpfile.js
[13:05:58] Starting 'clean'...
[13:05:58] Starting 'lint'...
[13:05:58] Starting 'build:lib'...
[13:05:59] Finished 'clean' after 628 ms
sharepoint/queryable.ts[264, 83]: block is empty

[13:06:03] Finished 'lint' after 5.19 s
[13:06:06] Finished 'build:lib' after 7.84 s
[13:06:06] Starting 'build'...
[13:06:06] Finished 'build' after 6.66 μs
toor@linux-jpyk:~/workspace/PnP-JS-Core> gulp package
[13:06:12] Using gulpfile ~/workspace/PnP-JS-Core/gulpfile.js
[13:06:12] Starting 'clean'...
[13:06:12] Starting 'lint'...
[13:06:12] Starting 'build:lib'...
[13:06:12] Starting 'package:defs'...
[13:06:12] Finished 'package:defs' after 2.17 ms
[13:06:13] Finished 'clean' after 799 ms
sharepoint/queryable.ts[264, 83]: block is empty

[13:06:21] Finished 'lint' after 9.22 s
[13:06:21] Finished 'build:lib' after 9.24 s
[13:06:21] Starting 'package:code'...
Hash: 357ca29215320de778d6af564902b593c4de8ca8
Version: webpack 1.14.0
Child
    Hash: 357ca29215320de778d6
    Version: webpack 1.14.0
    Time: 10779ms
         Asset    Size  Chunks             Chunk Names
        pnp.js  373 kB       0  [emitted]  main
    pnp.js.map  378 kB       0  [emitted]  main
......
 WARNING in pnp.min.js from UglifyJs
    Condition left of && always false [./lib/utils/util.js:2,18]
    Condition left of || always false [./lib/utils/util.js:2,18]
[13:06:32] Finished 'package:code' after 11 s
[13:06:32] Starting 'package'...
[13:06:32] Finished 'package' after 6.67 μs
toor@linux-jpyk:~/workspace/PnP-JS-Core> 

```

**Comment by RoelVB** [comment]
I did an `npm install` before the `gulp build`

**Comment by patrick-rodgers** [comment]
@RoelVB - did you pull it into a new folder? I think it should work if you

1. pull into new folder
2. gulp package
3. in your project folder (the app you are writing) do an npm install file:\\c:\path\to\folder\from\step\1

That will install the npm package from your hd instead of the service, but reflect the updated code you just pulled down.

**Comment by patrick-rodgers** [comment]
thanks @mauricionr!

**Comment by RoelVB** [comment]
I tried it again to be sure.
1. Created a new folder
2. Pulled the branch
3. Did `npm install`
4. Did `gulp package`
5. Got a lot of errors

**Comment by patrick-rodgers** [comment]
Going to be pushing out 2.0.1 that will resolve this, but will come with new guidance for using the library within SPFx. You'll have to pass the context object to the library. In talking with engineering that will be the only reliable method moving forward to gain context.

**Comment by patrick-rodgers** [comment]
Resolved in 2.0.1, please see [article](https://github.com/SharePoint/PnP-JS-Core/wiki/Using-sp--pnp-js-in-SharePoint-Framework) for details. Thanks!
